### ISSUE TITLE
Browsing is blocked

### ISSUE THREAD

**Issue by N3ars** [fuwwy/spotify-adblocker#8]
Hi there, when i want to search music or navigate on the menu, i have the error pages, they are not loaded, only thing i can do is listening to my liked playlist
i also have this error 
```
proxy error: Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:213:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
```
any help, thanks!

**Comment by N3ars** [comment]
EDIT :
For those who are interested I had to add these lines in the whitelist to be able to navigate :

"gew-dealer.spotify.com", "gew-spclient.spotify.com", "api.spotify.com", "api-partner.spotify.com",

**Comment by fuwwy** [comment]
@N3ars Do you know what gew-dealer and gew-spclient are used for?
